### ISSUE TITLE
Error in setDataRate

### ISSUE THREAD

**Issue by dquadros** [jpbarraca/pynrf24#20]
Should be
setup &= ~(NRF24.RF_DR_LOW | NRF24.RF_DR_HIGH)
instead of
setup &= (~NRF24.RF_DR_LOW | NRF24.RF_DR_HIGH)
This error messes up the default rate of 1Mbps (radio will be programmed to 2Mbps instead)

**Comment by n0skill** [comment]
I just sent a pull request to fix the issue, it should be fixed soon.

**Comment by dquadros** [comment]
I did a fork, made a few changes and added comments to the code. Some of the changes are more about the way I code and probably should not be moved back to the master. So far I'm using the code in a very specific environment, latter on I hope to make more abrangent tests.


Daniel

Enviado do Yahoo Mail no Android

De:"Noskill" <notifications@github.com>
Data:8:30 seg, 12 de out de AM
Assunto:Re: [pynrf24] Error in setDataRate (#20)

I just sent a pull request to fix the issue, it should be fixed soon.

**Comment by n0skill** [comment]
Okay then, I'll just close my request. Thanks for letting me know :)

**Comment by jpbarraca** [comment]
Some of the things you are changing really make sense. I will try to update my version accordingly. In alternative, send a pull request.
