### ISSUE TITLE
python2 or python3

### ISSUE THREAD

**Issue by pietrondo** [jpbarraca/pynrf24#29]
Hi.
I have a beaglebone... could I use python3 or only python2?
thx

**Comment by GreeningGalaxy** [comment]
I am not a developer of this project, but I just started working with it and I can confirm that the code works in both Python 2.7 and Python 3.4. If you want to install it for Python 3 on a system whose default Python interpreter is 2.7, the easiest way is to edit the shebang line of `setup.py` and change `/usr/bin/env python` to `/usr/bin/env python3`, then run it (`build` and `install`) again.
