### ISSUE TITLE
Incorrect use of Function GPIO.wait_for_edge() in irqWait

### ISSUE THREAD

**Issue by t1ngyu** [jpbarraca/pynrf24#37]
1. the `timeout` argument must used as keyword argument, otherwise it will no effect.
2. the return value is `None` for timeout, or `the pin number` for edge detected.

So, modify the code as following:
```
return GPIO.wait_for_edge(self.irq_pin, GPIO.FALLING, timeout=timeout) == self.irq_pin
```

**Comment by JoeLaCleDeDouze** [comment]
Hello @jpbarraca, 
I seem to have an invalid syntax SyntaxError when installing the library with python. The issue appears on line 328.(
Reverting this line to the previous revision seems to work better.
