### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by promistrio** [jpbarraca/pynrf24#38]
Hi! After python examples/recv.py
`Traceback (most recent call last):
  File "examples/recv.py", line 14, in <module>
    radio.begin(1, 0, "P8_23", "P8_24")
  File "/usr/local/lib/python2.7/dist-packages/nrf24.py", line 233, in begin
    self.spidev.open(major, minor)
IOError: [Errno 2] No such file or directory
`

**Comment by psmitty7373** [comment]
Are you using a pi, by chance?  Try calling begin with begin(0, 0... instead of begin(1, 0...
